// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package wesdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createMoves = `-- name: CreateMoves :many
INSERT INTO moves (wes_id, status, description)
SELECT $1::uuid, UNNEST($2::move_status[]), UNNEST($3::text[])
RETURNING id, wes_id, status, description, created_at
`

type CreateMovesParams struct {
	Column1 uuid.UUID    `json:"column_1"`
	Column2 []MoveStatus `json:"column_2"`
	Column3 []string     `json:"column_3"`
}

func (q *Queries) CreateMoves(ctx context.Context, arg CreateMovesParams) ([]Move, error) {
	rows, err := q.db.QueryContext(ctx, createMoves, arg.Column1, pq.Array(arg.Column2), pq.Array(arg.Column3))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Move{}
	for rows.Next() {
		var i Move
		if err := rows.Scan(
			&i.ID,
			&i.WesID,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWes = `-- name: CreateWes :one
INSERT INTO wes (height)
VALUES ($1)
RETURNING id, height, created_at, updated_at
`

func (q *Queries) CreateWes(ctx context.Context, height string) (Wes, error) {
	row := q.db.QueryRowContext(ctx, createWes, height)
	var i Wes
	err := row.Scan(
		&i.ID,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllMovesByWesID = `-- name: GetAllMovesByWesID :many
SELECT id, wes_id, status, description, created_at
FROM moves
WHERE wes_id = $1
ORDER BY created_at
`

func (q *Queries) GetAllMovesByWesID(ctx context.Context, wesID uuid.UUID) ([]Move, error) {
	rows, err := q.db.QueryContext(ctx, getAllMovesByWesID, wesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Move{}
	for rows.Next() {
		var i Move
		if err := rows.Scan(
			&i.ID,
			&i.WesID,
			&i.Status,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWesByID = `-- name: GetWesByID :one
SELECT id, height, created_at, updated_at
FROM wes
WHERE id = $1
`

func (q *Queries) GetWesByID(ctx context.Context, id uuid.UUID) (Wes, error) {
	row := q.db.QueryRowContext(ctx, getWesByID, id)
	var i Wes
	err := row.Scan(
		&i.ID,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
