// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package wesdb

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type MoveStatus string

const (
	MoveStatusWessendoBagre                       MoveStatus = "Wes sendo Bagre"
	MoveStatusWesfezaboa                          MoveStatus = "Wes fez a boa"
	MoveStatusWescomolivrodebaixodobrao           MoveStatus = "Wes com o livro de baixo do braço"
	MoveStatusWesesquecendoahistoriaenquantoconta MoveStatus = "Wes esquecendo a historia enquanto conta"
)

func (e *MoveStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MoveStatus(s)
	case string:
		*e = MoveStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MoveStatus: %T", src)
	}
	return nil
}

type NullMoveStatus struct {
	MoveStatus MoveStatus `json:"move_status"`
	Valid      bool       `json:"valid"` // Valid is true if MoveStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMoveStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MoveStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MoveStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMoveStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MoveStatus), nil
}

type Move struct {
	ID          uuid.UUID  `json:"id"`
	WesID       uuid.UUID  `json:"wes_id"`
	Status      MoveStatus `json:"status"`
	Description string     `json:"description"`
	CreatedAt   time.Time  `json:"created_at"`
}

type Wes struct {
	ID        uuid.UUID `json:"id"`
	Height    string    `json:"height"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
