// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package wesdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateMoves(ctx context.Context, arg CreateMovesParams) ([]Move, error)
	CreateWes(ctx context.Context, height string) (Wes, error)
	GetAllMovesByWesID(ctx context.Context, wesID uuid.UUID) ([]Move, error)
	GetWesByID(ctx context.Context, id uuid.UUID) (Wes, error)
}

var _ Querier = (*Queries)(nil)
